# Site settings
title: 今晚我想來篇優質好文
description: 部落格
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lltyzer.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: lltyzer
user_description: YOLO
user_title: You only live once.
email: lltyzer2002@gmail.com
twitter_username: lltyzer
github_username:  lltyzer
gplus_username:  lorem_ipsum
disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: 主頁
    url: /
  - title: 分類
    url: /series
  - title: 標籤
    url: /tags
  - title: 關於
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
